export enum ExpenseCategory {
  FAMILY = 'FAMILY',
  LEISURE = 'LEISURE',
  HOUSING = 'HOUSING',
  PAYMENTS = 'PAYMENTS',
  HEALTH = 'HEALTH',
  SERVICES = 'SERVICES',
  TRANSPORTATION = 'TRANSPORTATION',
  CLOTHING = 'CLOTHING',
  FOOD = 'FOOD',
  CAR = 'CAR',
  EDUCATION = 'EDUCATION'
}
